# Generated by Django 3.0.6 on 2020-06-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('email', models.CharField(max_length=100, verbose_name='メールアドレス')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
            ],
        ),
    ]
